### PR TITLE
Add IE11 build config

### PR DESCRIPTION
**Pull request by jorisre**
👋🏻 

Related to https://github.com/react-hook-form/resolvers/issues/64#issuecomment-716622211

This PR add the IE11 build with the right version of `react-hook-form`. Similar to https://github.com/react-hook-form/resolvers/pull/68

Output:
Screen Shot 2020-10-26 at 19 24 27

### CODE REVIEW

**Comment by c0d3x** [comment]
Any updates on this?

**Comment by jorisre** [comment]
@bluebill1049 👋 when you have time, can you review this PR please ? :) Thanks

**Comment by bluebill1049** [comment]
sorry for the delay! will do @jorisre 👍

**Comment by c0d3x** [comment]
Sorry to be nagging 😄  but we need this IE11 fix for production last week! 💯

**Comment by jorisre** [comment]
@bluebill1049 Can we merge or close that one ?

**Comment by bluebill1049** [comment]
Let's close this one.

**Pull request closed without merging**
